import Image from "next/image";
import Link from "next/link";

import { cn } from "@/lib/cn";
import { site } from "@/lib/site";

const SIZES = {
  header: "h-14 w-40 object-contain sm:h-16 sm:w-48 lg:h-[72px] lg:w-56",
  footer: "h-16 w-48 object-contain sm:h-[72px] sm:w-56",
} as const;

type BrandMarkProps = {
  /** "dark" renders the charcoal wordmark for light surfaces. */
  tone?: "dark" | "light";
  size?: keyof typeof SIZES;
  className?: string;
  /** Omit the link when the mark sits inside another link or a heading. */
  asLink?: boolean;
  /**
   * Start the download immediately instead of lazily. For a mark that is on
   * screen at first paint.
   *
   * Paired with `fetchPriority="low"` below, which is what actually keeps the
   * mark out of the way. React 19 preloads every server-rendered <img> unless
   * it is lazy or explicitly low priority, so eager loading alone put two
   * <link rel=preload> tags in the head ahead of the hero photograph - the
   * page's real LCP element - and on throttled 4G the hero paid for it. Low
   * priority drops the preload and still starts the download immediately, so
   * the mark never flashes in but never jumps the queue either. It renders
   * fourteen pixels tall; it can afford to wait behind a full-screen photo.
   */
  eager?: boolean;
};

/**
 * The SAVOY wordmark.
 *
 * Two variants are generated by the image pipeline from the single supplied
 * PNG: the original white mark for dark and yellow surfaces, and a recoloured
 * charcoal twin for the warm-white surface the site mostly uses.
 */
export function BrandMark({
  size = "header",
  className,
  asLink = true,
  eager = false,
}: BrandMarkProps) {
  const image = (
    <Image
      src="/brand/savoy-logo-transparent.png"
      alt={site.name}
      width={760}
      height={272}
      loading={eager ? "eager" : "lazy"}
      fetchPriority="low"
      className={SIZES[size]}
    />
  );

  if (!asLink) {
    return <span className={cn("inline-flex items-center", className)}>{image}</span>;
  }

  return (
    <Link
      href="/"
      className={cn("inline-flex items-center", className)}
      aria-label={`${site.name} - beranda`}
    >
      {image}
    </Link>
  );
}
